my_list = []
print(my_list)
my_list.append(10)
print(my_list)
my_list.append(20)
print(my_list)
my_list.append(30)
print(my_list)
my_list.append(40)
print(my_list)
my_list.insert(1,15)
print(my_list)
list_2 = [50, 60, 70]
print(list_2)
my_list.extend(list_2)
print(my_list)
my_list.pop(-1)
print(my_list)
my_list.sort
print(my_list)
print(my_list.index(30))